// <auto-generated />
using System;
using CoreCnice.Connect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCnice.Migrations
{
    [DbContext(typeof(BulSoftCmsConnectContext))]
    [Migration("20181002082537_CORE_DB")]
    partial class CORE_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_AD_ITEM", b =>
                {
                    b.Property<int>("AD_ITEM_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AD_ITEM_CLICKCOUNT");

                    b.Property<string>("AD_ITEM_CODE");

                    b.Property<int?>("AD_ITEM_COUNT");

                    b.Property<DateTime?>("AD_ITEM_DATEFROM");

                    b.Property<DateTime?>("AD_ITEM_DATETO");

                    b.Property<string>("AD_ITEM_DESC");

                    b.Property<string>("AD_ITEM_FIELD1");

                    b.Property<string>("AD_ITEM_FIELD2");

                    b.Property<string>("AD_ITEM_FILENAME");

                    b.Property<int?>("AD_ITEM_HEIGHT");

                    b.Property<int?>("AD_ITEM_LANGUAGE");

                    b.Property<int?>("AD_ITEM_ORDER");

                    b.Property<int?>("AD_ITEM_POSITION");

                    b.Property<DateTime?>("AD_ITEM_PUBLISHDATE");

                    b.Property<string>("AD_ITEM_TARGET");

                    b.Property<int?>("AD_ITEM_TYPE");

                    b.Property<string>("AD_ITEM_URL");

                    b.Property<int?>("AD_ITEM_WIDTH");

                    b.HasKey("AD_ITEM_ID");

                    b.ToTable("ESHOP_AD_ITEM");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_AD_ITEM_CAT", b =>
                {
                    b.Property<int>("AD_ITEM_CAT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AD_ITEM_ID");

                    b.Property<int?>("CAT_ID");

                    b.HasKey("AD_ITEM_CAT_ID");

                    b.ToTable("ESHOP_AD_ITEM_CAT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_BASKET", b =>
                {
                    b.Property<int>("BASKET_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BASKET_AMOUNT");

                    b.Property<decimal>("BASKET_PRICE");

                    b.Property<DateTime>("BASKET_PUBLISHDATE");

                    b.Property<int>("BASKET_QUANTITY");

                    b.Property<DateTime>("BASKET_UPDATE");

                    b.Property<int>("CUSTOMER_ID");

                    b.Property<Guid>("CUSTOMER_OID");

                    b.Property<int>("NEWS_ID");

                    b.HasKey("BASKET_ID");

                    b.ToTable("ESHOP_BASKET");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_CATEGORIES", b =>
                {
                    b.Property<int>("CAT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CAT_CODE");

                    b.Property<string>("CAT_DESC");

                    b.Property<string>("CAT_DESC_EN");

                    b.Property<string>("CAT_IMAGE1");

                    b.Property<string>("CAT_IMAGE2");

                    b.Property<string>("CAT_NAME");

                    b.Property<int?>("CAT_PAGEITEM");

                    b.Property<int?>("CAT_PARENT_ID");

                    b.Property<int?>("CAT_PERIOD");

                    b.Property<int?>("CAT_PERIOD_ORDER");

                    b.Property<int?>("CAT_POSITION");

                    b.Property<int?>("CAT_ROWITEM");

                    b.Property<string>("CAT_SEO_DESC");

                    b.Property<string>("CAT_SEO_KEYWORD");

                    b.Property<string>("CAT_SEO_TITLE");

                    b.Property<string>("CAT_SEO_TITLE_EN");

                    b.Property<string>("CAT_SEO_URL");

                    b.Property<int?>("CAT_SHOWFOOTER");

                    b.Property<int?>("CAT_SHOWHOME");

                    b.Property<int?>("CAT_STATUS");

                    b.Property<string>("CAT_TARGET");

                    b.Property<int?>("CAT_TYPE");

                    b.Property<string>("CAT_URL");

                    b.HasKey("CAT_ID");

                    b.ToTable("ESHOP_CATEGORIES");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_COLOR", b =>
                {
                    b.Property<int>("COLOR_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("COLOR_ACTIVE");

                    b.Property<string>("COLOR_DESC");

                    b.Property<string>("COLOR_FIELD1");

                    b.Property<string>("COLOR_NAME");

                    b.Property<int>("COLOR_PRIORITY");

                    b.HasKey("COLOR_ID");

                    b.ToTable("ESHOP_COLOR");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_COMPA", b =>
                {
                    b.Property<int>("NEWS_COMPA_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CUSTOMER_ID");

                    b.Property<int>("NEWS_ID");

                    b.Property<int>("STATUS");

                    b.HasKey("NEWS_COMPA_ID");

                    b.ToTable("ESHOP_COMPA");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_CONFIG", b =>
                {
                    b.Property<int>("CONFIG_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CONFIG_ADD");

                    b.Property<string>("CONFIG_CONTACT");

                    b.Property<string>("CONFIG_DESCRIPTION");

                    b.Property<string>("CONFIG_EMAIL");

                    b.Property<string>("CONFIG_FACEBOOK");

                    b.Property<string>("CONFIG_FAVICON");

                    b.Property<string>("CONFIG_FOOTER");

                    b.Property<string>("CONFIG_GOOGLE");

                    b.Property<int?>("CONFIG_HITCOUNTER");

                    b.Property<string>("CONFIG_KEYWORD");

                    b.Property<int?>("CONFIG_LANGUAGE");

                    b.Property<string>("CONFIG_NAME");

                    b.Property<string>("CONFIG_NAME_US");

                    b.Property<int?>("CONFIG_ORDER");

                    b.Property<string>("CONFIG_PASSWORD");

                    b.Property<string>("CONFIG_PORT");

                    b.Property<string>("CONFIG_SMTP");

                    b.Property<string>("CONFIG_TITLE");

                    b.HasKey("CONFIG_ID");

                    b.ToTable("ESHOP_CONFIG");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_CONTACT", b =>
                {
                    b.Property<int>("CONTACT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CONTACT_ADDRESS");

                    b.Property<string>("CONTACT_ANSWER");

                    b.Property<string>("CONTACT_CONTENT");

                    b.Property<string>("CONTACT_EMAIL");

                    b.Property<string>("CONTACT_NAME");

                    b.Property<string>("CONTACT_PHONE");

                    b.Property<DateTime?>("CONTACT_PUBLISHDATE");

                    b.Property<int?>("CONTACT_SHOWTYPE");

                    b.Property<string>("CONTACT_TITLE");

                    b.Property<int?>("CONTACT_TYPE");

                    b.HasKey("CONTACT_ID");

                    b.ToTable("ESHOP_CONTACT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_CUSTOMER", b =>
                {
                    b.Property<int>("CUSTOMER_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CUSTOMER_ADDRESS");

                    b.Property<string>("CUSTOMER_FIELD1");

                    b.Property<string>("CUSTOMER_FULLNAME");

                    b.Property<string>("CUSTOMER_IP");

                    b.Property<int?>("CUSTOMER_NEWSLETTER");

                    b.Property<Guid?>("CUSTOMER_OID");

                    b.Property<string>("CUSTOMER_PHONE1");

                    b.Property<DateTime?>("CUSTOMER_PUBLISHDATE");

                    b.Property<string>("CUSTOMER_PW");

                    b.Property<int?>("CUSTOMER_REMAIN");

                    b.Property<int?>("CUSTOMER_SEX");

                    b.Property<int?>("CUSTOMER_SHOWTYPE");

                    b.Property<int?>("CUSTOMER_TOTAL_POINT");

                    b.Property<string>("CUSTOMER_UN");

                    b.Property<DateTime?>("CUSTOMER_UPDATE");

                    b.HasKey("CUSTOMER_ID");

                    b.ToTable("ESHOP_CUSTOMER");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_EMAIL", b =>
                {
                    b.Property<int>("EMAIL_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EMAIL_BCC");

                    b.Property<string>("EMAIL_CC");

                    b.Property<int?>("EMAIL_CUSTOMER_ALL");

                    b.Property<string>("EMAIL_DESC");

                    b.Property<string>("EMAIL_FROM");

                    b.Property<DateTime?>("EMAIL_PUBLISHDATE");

                    b.Property<int?>("EMAIL_PUBLISHDATE_DAY");

                    b.Property<DateTime?>("EMAIL_PUBLISHDATE_START");

                    b.Property<int>("EMAIL_STT");

                    b.Property<string>("EMAIL_TO");

                    b.Property<int?>("USER_ID");

                    b.HasKey("EMAIL_ID");

                    b.ToTable("ESHOP_EMAIL");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_GIFT", b =>
                {
                    b.Property<int>("GIFT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GIFT_AMOUNT");

                    b.Property<string>("GIFT_CONTENT");

                    b.Property<string>("GIFT_DESC");

                    b.Property<string>("GIFT_IMAGE");

                    b.Property<int>("GIFT_MAX_AMOUNT");

                    b.Property<string>("GIFT_NAME");

                    b.Property<int>("GIFT_POINT");

                    b.Property<DateTime>("GIFT_PULISHDATE");

                    b.Property<DateTime>("GIFT_USE_PUBLISHDATE");

                    b.Property<int>("GIF_ACTIVE");

                    b.HasKey("GIFT_ID");

                    b.ToTable("ESHOP_GIFT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_GROUP", b =>
                {
                    b.Property<int>("GROUP_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ESHOP_USERUSER_ID");

                    b.Property<string>("GROUP_CODE");

                    b.Property<string>("GROUP_NAME");

                    b.Property<DateTime?>("GROUP_PUBLISHDATE");

                    b.Property<int?>("GROUP_TYPE");

                    b.HasKey("GROUP_ID");

                    b.HasIndex("ESHOP_USERUSER_ID");

                    b.ToTable("ESHOP_GROUP");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_GROUP_CAT", b =>
                {
                    b.Property<int>("GROUP_CAT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CAT_ID");

                    b.Property<int>("GROUP_ID");

                    b.HasKey("GROUP_CAT_ID");

                    b.ToTable("ESHOP_GROUP_CAT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_MONEY", b =>
                {
                    b.Property<int>("NEWS_MONEY_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NEWS_MONEY_ACTIVE");

                    b.Property<string>("NEWS_MONEY_BEGIN");

                    b.Property<string>("NEWS_MONEY_END");

                    b.Property<string>("NEWS_MONEY_TITLE");

                    b.HasKey("NEWS_MONEY_ID");

                    b.ToTable("ESHOP_MONEY");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS", b =>
                {
                    b.Property<int>("NEWS_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NEWS_CODE");

                    b.Property<int?>("NEWS_COUNT");

                    b.Property<string>("NEWS_DESC");

                    b.Property<int?>("NEWS_FEEDBACKTYPE");

                    b.Property<string>("NEWS_FILEHTML");

                    b.Property<string>("NEWS_IMAGE1");

                    b.Property<string>("NEWS_IMAGE2");

                    b.Property<string>("NEWS_IMAGE3");

                    b.Property<string>("NEWS_IMAGE4");

                    b.Property<int?>("NEWS_ORDER");

                    b.Property<int?>("NEWS_ORDER_PERIOD");

                    b.Property<int?>("NEWS_PERIOD");

                    b.Property<decimal?>("NEWS_PRICE1");

                    b.Property<decimal?>("NEWS_PRICE2");

                    b.Property<decimal?>("NEWS_PRICE3");

                    b.Property<int?>("NEWS_PRINTTYPE");

                    b.Property<DateTime?>("NEWS_PUBLISHDATE");

                    b.Property<int?>("NEWS_SENDDATE");

                    b.Property<int?>("NEWS_SENDEMAIL");

                    b.Property<string>("NEWS_SEO_DESC");

                    b.Property<string>("NEWS_SEO_KEYWORD");

                    b.Property<string>("NEWS_SEO_TITLE");

                    b.Property<string>("NEWS_SEO_URL");

                    b.Property<int?>("NEWS_SHOWINDETAIL");

                    b.Property<int?>("NEWS_SHOWTYPE");

                    b.Property<string>("NEWS_TARGET");

                    b.Property<string>("NEWS_TITLE");

                    b.Property<int?>("NEWS_TYPE");

                    b.Property<DateTime?>("NEWS_UPDATE");

                    b.Property<string>("NEWS_URL");

                    b.HasKey("NEWS_ID");

                    b.ToTable("ESHOP_NEWS");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_ATT", b =>
                {
                    b.Property<int>("NEWS_ATT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EXT_ID");

                    b.Property<string>("NEWS_ATT_FIELD1");

                    b.Property<string>("NEWS_ATT_FIELD2");

                    b.Property<string>("NEWS_ATT_FIELD3");

                    b.Property<string>("NEWS_ATT_FILE");

                    b.Property<string>("NEWS_ATT_NAME");

                    b.Property<int>("NEWS_ATT_ORDER");

                    b.Property<string>("NEWS_ATT_URL");

                    b.Property<int>("NEWS_ID");

                    b.HasKey("NEWS_ATT_ID");

                    b.ToTable("ESHOP_NEWS_ATT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_CAT", b =>
                {
                    b.Property<int>("NEWS_CAT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CAT_ID");

                    b.Property<int>("NEWS_ID");

                    b.HasKey("NEWS_CAT_ID");

                    b.ToTable("ESHOP_NEWS_CAT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_COMMENT", b =>
                {
                    b.Property<int>("COMMENT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COMMENT_CONTENT");

                    b.Property<string>("COMMENT_EMAIL");

                    b.Property<string>("COMMENT_FIELD1");

                    b.Property<string>("COMMENT_FIELD2");

                    b.Property<string>("COMMENT_NAME");

                    b.Property<DateTime>("COMMENT_PUBLISHDATE");

                    b.Property<int>("COMMENT_STATUS");

                    b.Property<int>("CUS_ID");

                    b.Property<int>("NEWS_ID");

                    b.HasKey("COMMENT_ID");

                    b.ToTable("ESHOP_NEWS_COMMENT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_IMAGE", b =>
                {
                    b.Property<int>("NEWS_IMG_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NEWS_ID");

                    b.Property<string>("NEWS_IMG_DESC");

                    b.Property<string>("NEWS_IMG_IMAGE1");

                    b.Property<int>("NEWS_IMG_ORDER");

                    b.Property<int>("NEWS_IMG_SHOWTYPE");

                    b.HasKey("NEWS_IMG_ID");

                    b.ToTable("ESHOP_NEWS_IMAGE");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_NEWS", b =>
                {
                    b.Property<int>("NEWS_NEWS_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NEWS_ID1");

                    b.Property<int>("NEWS_ID2");

                    b.HasKey("NEWS_NEWS_ID");

                    b.ToTable("ESHOP_NEWS_NEWS");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_NEWS_PROPERTIES", b =>
                {
                    b.Property<int>("NEWS_PROP_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NEWS_ID");

                    b.Property<int>("PROP_ID");

                    b.HasKey("NEWS_PROP_ID");

                    b.ToTable("ESHOP_NEWS_PROPERTIES");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_ONLINE", b =>
                {
                    b.Property<int>("ONLINE_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CUS_ID");

                    b.Property<int?>("ONLINE_ACTIVE");

                    b.Property<string>("ONLINE_COMBACK");

                    b.Property<string>("ONLINE_DESC");

                    b.Property<string>("ONLINE_DESC_EN");

                    b.Property<Guid?>("ONLINE_GUID");

                    b.Property<string>("ONLINE_IMAGE");

                    b.Property<string>("ONLINE_IP");

                    b.Property<string>("ONLINE_LINK");

                    b.Property<string>("ONLINE_LOCATION");

                    b.Property<string>("ONLINE_NICKNAME");

                    b.Property<int>("ONLINE_ORDER");

                    b.Property<DateTime?>("ONLINE_OUT_DATE");

                    b.Property<DateTime?>("ONLINE_START_BEGIN_DATE");

                    b.Property<int>("ONLINE_TYPE");

                    b.HasKey("ONLINE_ID");

                    b.ToTable("ESHOP_ONLINE");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_ORDER", b =>
                {
                    b.Property<int>("ORDER_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CUSTOMER_ID");

                    b.Property<string>("ORDER_CODE");

                    b.Property<int?>("ORDER_DAY");

                    b.Property<string>("ORDER_DESC");

                    b.Property<string>("ORDER_IP");

                    b.Property<int?>("ORDER_MONTH");

                    b.Property<DateTime?>("ORDER_PUBLISHDATE");

                    b.Property<int?>("ORDER_STATUS");

                    b.Property<decimal?>("ORDER_TOTAL_ALL");

                    b.Property<DateTime?>("ORDER_UPDATE");

                    b.Property<int?>("ORDER_YEAR");

                    b.Property<string>("RECEIVER_ADDRESS");

                    b.Property<string>("RECEIVER_EMAIL");

                    b.Property<string>("RECEIVER_FULLNAME");

                    b.Property<string>("RECEIVER_PHONE1");

                    b.HasKey("ORDER_ID");

                    b.ToTable("ESHOP_ORDER");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_ORDER_ITEM", b =>
                {
                    b.Property<int>("ITEM_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ITEM_PRICE");

                    b.Property<DateTime>("ITEM_PUBLISDATE");

                    b.Property<float>("ITEM_QUANTITY");

                    b.Property<decimal>("ITEM_SUBTOTAL");

                    b.Property<DateTime>("ITEM_UPDATE");

                    b.Property<int>("NEWS_ID");

                    b.Property<int>("ORDER_ID");

                    b.Property<int>("UNIT_ID");

                    b.HasKey("ITEM_ID");

                    b.ToTable("ESHOP_ORDER_ITEM");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_PROPERTIES", b =>
                {
                    b.Property<int>("PROP_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PROP_ACTIVE");

                    b.Property<string>("PROP_DESC");

                    b.Property<string>("PROP_NAME");

                    b.Property<int>("PROP_PARENT_ID");

                    b.Property<int?>("PROP_RANK");

                    b.HasKey("PROP_ID");

                    b.ToTable("ESHOP_PROPERTIES");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_STORE", b =>
                {
                    b.Property<int>("ESHOP_STORE_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ESHOP_STORE_ACTIVE");

                    b.Property<string>("ESHOP_STORE_ADDRESS");

                    b.Property<string>("ESHOP_STORE_EMAIL");

                    b.Property<string>("ESHOP_STORE_IMAGE");

                    b.Property<string>("ESHOP_STORE_NAME");

                    b.Property<string>("ESHOP_STORE_PHONE");

                    b.Property<int?>("ESHOP_STORE_TYPE");

                    b.Property<string>("ESHOP_STORE_UN");

                    b.HasKey("ESHOP_STORE_ID");

                    b.ToTable("ESHOP_STORE");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_THEME", b =>
                {
                    b.Property<int>("ESHOP_THEME_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CAT_ID");

                    b.Property<string>("ESHOP_THEME_LINK_FILE");

                    b.Property<string>("ESHOP_THEME_NAME");

                    b.Property<int>("ESHOP_THEME_TYPE");

                    b.Property<int>("NEWS_ID");

                    b.HasKey("ESHOP_THEME_ID");

                    b.ToTable("ESHOP_THEME");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_UNITS", b =>
                {
                    b.Property<int>("UNIT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UNIT_ACTIVE");

                    b.Property<string>("UNIT_DESC");

                    b.Property<string>("UNIT_NAME");

                    b.Property<decimal>("UNIT_PRICE");

                    b.HasKey("UNIT_ID");

                    b.ToTable("ESHOP_UNITS");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_USER", b =>
                {
                    b.Property<int>("USER_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GROUP_ID");

                    b.Property<string>("SALT");

                    b.Property<int?>("USER_ACTIVE");

                    b.Property<DateTime?>("USER_END_WORK");

                    b.Property<string>("USER_NAME");

                    b.Property<DateTime?>("USER_PUBLISHDATE");

                    b.Property<string>("USER_PW");

                    b.Property<DateTime?>("USER_START_WORK");

                    b.Property<int?>("USER_TYPE");

                    b.Property<string>("USER_UN");

                    b.HasKey("USER_ID");

                    b.ToTable("ESHOP_USER");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_USER_GIFT", b =>
                {
                    b.Property<int>("USER_GIFT_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CUSTOMER_ID");

                    b.Property<int>("GIFT_ID");

                    b.Property<int>("USER_GIFT_ACTIVE");

                    b.Property<DateTime>("USER_GIFT_DATE");

                    b.Property<string>("USER_GIFT_DESC");

                    b.Property<string>("USER_GIFT_FEILD");

                    b.Property<string>("USER_GIFT_FIELD1");

                    b.Property<int>("USER_GIFT_QUANTITY");

                    b.Property<int>("USER_GIFT_STATUS");

                    b.HasKey("USER_GIFT_ID");

                    b.ToTable("ESHOP_USER_GIFT");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_WEBLINKS", b =>
                {
                    b.Property<int>("WEBSITE_LINKS_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("WEBSITE_LINKS_LANGUAGE");

                    b.Property<string>("WEBSITE_LINKS_NAME");

                    b.Property<int>("WEBSITE_LINKS_ORDER");

                    b.Property<string>("WEBSITE_LINKS_TARGET");

                    b.Property<string>("WEBSITE_LINKS_URL");

                    b.Property<int>("WEBSITE_LINK_PE_ID");

                    b.Property<int>("WEBSITE_RANK");

                    b.HasKey("WEBSITE_LINKS_ID");

                    b.ToTable("ESHOP_WEBLINKS");
                });

            modelBuilder.Entity("CoreCnice.Domain.MODULE", b =>
                {
                    b.Property<int>("NEWS_MODULE_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NEWS_MODULE_LANG");

                    b.Property<string>("NEWS_MODULE_NAME");

                    b.Property<int>("NEWS_MODULE_ORDER");

                    b.Property<int>("NEWS_MODULE_STATUS");

                    b.HasKey("NEWS_MODULE_ID");

                    b.ToTable("MODULE");
                });

            modelBuilder.Entity("CoreCnice.Domain.ESHOP_GROUP", b =>
                {
                    b.HasOne("CoreCnice.Domain.ESHOP_USER")
                        .WithMany("GroupList")
                        .HasForeignKey("ESHOP_USERUSER_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
